export const countryOptions = [
  { value: "us", label: "United States of America" },
  // { value: 'at', label: 'Austria' },
  { value: "au", label: "Australia" },
  // { value: 'be', label: 'Belgium' },
  // { value: 'bg', label: 'Bulgaria' },
  // { value: 'br', label: 'Brazil' },
  { value: "ca", label: "Canada" },
  // { value: 'ch', label: 'Switzerland' },
  // { value: 'cy', label: 'Cyprus' },
  // { value: 'cz', label: 'Czech Republic' },
  // { value: 'de', label: 'Germany' },
  // { value: 'dk', label: 'Denmark' },
  // { value: 'ee', label: 'Estonia' },
  // { value: 'es', label: 'Spain' },
  // { value: 'fi', label: 'Finland' },
  // { value: 'fr', label: 'France' },
  // { value: 'gb', label: 'United Kingdom' },
  // { value: 'gr', label: 'Greece' },
  // { value: 'hk', label: 'Hong Kong' },
  // { value: 'hu', label: 'Hungary' },
  // { value: 'ie', label: 'Ireland' },
  // { value: 'it', label: 'Italy' },
  // { value: 'jp', label: 'Japan' },
  // { value: 'lt', label: 'Lithuania' },
  // { value: 'lu', label: 'Luxembourg' },
  // { value: 'lv', label: 'Latvia' },
  // { value: 'mt', label: 'Malta' },
  { value: "mx", label: "Mexico" },
  // { value: 'my', label: 'Malaysia' },
  // { value: 'nl', label: 'Netherlands' },
  // { value: 'no', label: 'Norway' },
  { value: "nz", label: "New Zealand" },
  // { value: 'pl', label: 'Poland' },
  // { value: 'pt', label: 'Portugal' },
  // { value: 'ro', label: 'Romania' },
  // { value: 'se', label: 'Sweden' },
  { value: "sg", label: "Singapore" },
  // { value: 'si', label: 'Slovenia' },
  // { value: 'sk', label: 'Slovakia' },
];
