export enum PageState {
  FIRST_LOAD = "FIRST_LOAD",
  LOADING = "LOADING",
  FINISHED = "FINISHED",
  FETCH_FIRST_PAGE = "FETCH_FIRST_PAGE",
  FETCH_NEXT_PAGE = "FETCH_NEXT_PAGE",
  EMPTY_TRANSACTIONS = "EMPTY_TRANSACTIONS"
}
