# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:16.13.0

pipelines:
  pull-requests:
    "**": #this runs as default for any branch not elsewhere defined
      - step:
          name: Build and test
          caches:
            - npm
          script:
            - npm ci --legacy-peer-deps
            # - npm ci --prefix=./projects/ui
            # - npm ci --prefix=./projects/mobile-app --legacy-peer-deps
            - npm -w projects/ui    run rollup
            - npm -w projects/mobile-app    run lint
            # FIXME: TODO: Workspaces is brittle - so here we're using --prefix to correctly run tests. This should be switched to --workspace when possible.
            - npm run -w projects/mobile-app test -- --ci --reporters=default --reporters=jest-junit  --watchAll=false
      - step:
          name: "Publish PR Chromatic"
          caches:
            - npm
          # Other pipeline configuration
          script:
            - npm ci  --legacy-peer-deps
            - npm -w projects/ui    run rollup
            - cd projects/mobile-app
            # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - npm run chromatic -- --exit-zero-on-changes --exit-once-uploaded --project-token=$CHROMATIC_PROJECT_TOKEN
  branches:
    develop:
      - step:
          name: "Publish to Chromatic"
          caches:
            - npm
          # Other pipeline configuration
          script:
            - npm -w projects/mobile-app ci
              # 👇 Runs Chromatic with the flag to prevent pipeline failure
            - npm  -w projects/mobile-app run chromatic -- --project-token=$CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes
  custom:
    build-increment:
      - step:
          name: "Update build version"
          script:
            - echo "Installing dependencies"
            - npm  -w projects/mobile-app ci
            - echo "Updating build version"
            - node  -w projects/mobile-app build-increment.js
            - git commit -am "Build Version Update"
definitions:
  caches:
    npm: $HOME/.npm
