query getAccountsByGeom($geom: GeometricSearchInput) {
  searchAccountsByGeom(geom: $geom) {
    id
    displayName
    userName
    image
    merchantProfileDetails {
      geom
      acceptsPayments
    }
  }
}
