query getBanks{
    getBanks{
        id,
        lastFour,
        nickname,
        country,
        accountHolder,
        account{
            userName,
            id
        }
    }
}
