query GetMissingStripeRequirements {
  me {
    merchantProfileDetails {
      countryCode
    }
  }
  missingStripeRequirements {
    persons {
      id
      name
      relationships
      missingFields {
        fieldName
        properties
      }
    }
    business {
      id
      name
      type
      missingFields {
        fieldName
        properties
      }
    }
  }
}