query GetMyMerchantProfile {
  myMerchantProfile {
    id
    displayName
    merchantType
    currency
    address {
      street
      streetAdditional
      city
      region
      postal
    }
    country {
      name
      alpha2
    }
    acceptsPayments
    countryCode
    payoutsEnabled
    businessDetails {
      type
      hasBanking
      hasOnboarded
    }
  }
}
