query GetWalletBalanceHistory($period: MarketPeriodInput) {
  getWalletBalanceHistory(period: $period) {
    totalFiatBalance
    start
    end
    minPrice
    maxPrice
    firstValidPointIndex
    history {
      price
      time
    }
  }
}
