import bankSvg from "assets/svgs/bank.svg";
import bankIconBlueSvg from "assets/svgs/bankIconBlue.svg";
import bankAddSvg from "assets/svgs/bank-add.svg";
import shoppingBagSvg from "assets/svgs/shopping-bag.svg";
import handCreditCardSvg from "assets/svgs/hand-credit-card.svg";
import qrSvg from "assets/svgs/QrIcon.svg";
import moneySvg from "assets/svgs/MoneyIcon.svg";
import gearSvg from "assets/svgs/GearIcon.svg";
import logoutSvg from "assets/svgs/LogoutIcon.svg";
import cardSvg from "assets/svgs/CardIcon.svg";
import envelopeSvg from "assets/svgs/EnvelopeIcon.svg";
import profileSvg from "assets/svgs/ProfileIcon.svg";
import questionSvg from "assets/svgs/QuestionIcon.svg";
import shieldSvg from "assets/svgs/ShieldIcon.svg";
import padlockSvg from "assets/svgs/PadlockIcon.svg";
import documentSvg from "assets/svgs/DocumentIcon.svg";
import cartSvg from "assets/svgs/CartIcon.svg";
import plusSvg from "assets/svgs/PlusSign.svg";
import plusPaddedSvg from "assets/svgs/PlusSignPadded.svg";
import chevronForwardSvg from "assets/svgs/ChevronForwardIcon.svg";
import investSvg from "assets/svgs/icon-invest.svg";
import bagSvg from "assets/svgs/icon-bag.svg";
import docSvg from "assets/svgs/icon-doc.svg";
import CalendarIconSvg from "assets/svgs/CalendarIcon.svg";
import TicketIconSvg from "assets/svgs/TicketIcon.svg";
import InfoIconSvg from "assets/svgs/InfoIcon.svg";
import CopyIconSvg from "assets/svgs/CopyIcon.svg";
import RocketSvg from "assets/svgs/rocket.svg";
import InterestCardBackgroundSvg from "assets/svgs/InterestCardBackground.svg";
import ForwardSvg from "assets/svgs/Forward.svg";
import AdvtGainingSvg from "assets/svgs/AdvtGaining.svg";
import invalidBankSvg from "assets/svgs/invalid-bank.svg";
import closeBankSvg from "assets/svgs/close-bank.svg";
import RecipientQRScanSvg from "assets/svgs/RecipientQRScan.svg";
import SendRecipientSvg from "assets/svgs/SendRecipient.svg";
import GainingSvg from "assets/svgs/Gaining.svg";
import InterestGainSvg from "assets/svgs/InterestGainIcon.svg";
import MarketingCallOutSvg from "assets/svgs/MarketingCallOut.svg";
import VectorSvg from "assets/svgs/Vector.svg";
import TransferSvg from "assets/svgs/Transfer.svg";
import UpSvg from "assets/svgs/Up.svg";
import DownSvg from "assets/svgs/Down.svg";
import ActionSvg from "assets/svgs/V2.svg";
import OnboardingBackgroundSvg from "assets/svgs/OnboardingBackground.svg";
import WalletSvg from "assets/svgs/Wallet.svg";
import WarningIconSvg from "assets/svgs/Warning-Icon.svg";
import BitcoinLogoSvg from "assets/svgs/bitcoin-logo.svg";
import TransferSuccessIconSvg from "assets/svgs/TransferSuccessIcon.svg";
import NoCoinSvg from "assets/svgs/NoCoin.svg";
import CryptoWalletSvg from "assets/svgs/CryptoWallet.svg";
import InfoIconDarkSvg from "assets/svgs/info-icon-dark.svg";
import CreditCardIconSvg from "assets/svgs/CreditCardIcon.svg";
import CelebrationIconSvg from "assets/svgs/CelebrationIcon.svg";
import ChevronRightFilledSvg from "assets/svgs/chevron-right-filled.svg";
import GovtIdSvg from "assets/svgs/GovtId.svg";
import PassportSvg from "assets/svgs/Passport.svg";

export const investIcon = investSvg;
export const bagIcon = bagSvg;
export const docIcon = docSvg;
export const bankIcon = bankSvg;
export const bankBlueIcon = bankIconBlueSvg;
export const bankAddIcon = bankAddSvg;
export const shoppingBagIcon = shoppingBagSvg;
export const handCreditCardIcon = handCreditCardSvg;
export const qrIcon = qrSvg;
export const moneyIcon = moneySvg;
export const logoutIcon = logoutSvg;
export const cardIcon = cardSvg;
export const envelopIcon = envelopeSvg;
export const profileIcon = profileSvg;
export const questionIcon = questionSvg;
export const shieldIcon = shieldSvg;
export const padlockIcon = padlockSvg;
export const gearIcon = gearSvg;
export const documentIcon = documentSvg;
export const plusIcon = plusSvg;
export const plusPaddedIcon = plusPaddedSvg;
export const cartIcon = cartSvg;
export const chevronForwardIcon = chevronForwardSvg;
export const CalendarIcon = CalendarIconSvg;
export const TicketIcon = TicketIconSvg;
export const InfoIcon = InfoIconSvg;
export const CopyIcon = CopyIconSvg;
export const RocketIcon = RocketSvg;
export const InterestCardBackground = InterestCardBackgroundSvg;
export const ForwardIcon = ForwardSvg;
export const AdvtGainingIcon = AdvtGainingSvg;
export const invalidBankIcon = invalidBankSvg;
export const closeBankIcon = closeBankSvg;
export const RecipientQRScanIcon = RecipientQRScanSvg;
export const SendRecipientIcon = SendRecipientSvg;
export const GainingIcon = GainingSvg;
export const InterestGainIcon = InterestGainSvg;
export const MarketingCallOutIcon = MarketingCallOutSvg;
export const VectorIcon = VectorSvg;
export const TransferIcon = TransferSvg;
export const UpIcon = UpSvg;
export const DownIcon = DownSvg;
export const ActionIcon = ActionSvg;
export const OnboardingBackgroundIcon = OnboardingBackgroundSvg;
export const WalletIcon = WalletSvg;
export const WarningIcon = WarningIconSvg;
export const TransferSuccessIcon = TransferSuccessIconSvg;
export const BitcoinLogoIcon = BitcoinLogoSvg;
export const NoCoinIcon = NoCoinSvg;
export const CryptoWalletIcon = CryptoWalletSvg;
export const InfoIconDark = InfoIconDarkSvg;
export const CreditCardIcon = CreditCardIconSvg;
export const CelebrationIcon = CelebrationIconSvg;
export const ChevronRightFilled = ChevronRightFilledSvg;
export const GovtId = GovtIdSvg;
export const Passport = PassportSvg;
